name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Fetch, clone
        env:
          GHTOKEN: ${{ secrets.GHTOKEN }}
        run: bash fetch.sh
        shell: bash

      - name: Source build
        env:
          GHTOKEN: ${{ secrets.GHTOKEN }}
        run: bash build.sh
        shell: bash

      - name: Patch apk
        run: bash patch.sh
        shell: bash

      - name: Sign apks
        run: bash sign.sh
        shell: bash

      - name: Upload revanced patched apk
        uses: actions/upload-artifact@v3
        with:
          name: revanced-nonroot
          path: ./revanced_signed.apk
          if-no-files-found: error

      - name: Upload revanced manager apk
        uses: actions/upload-artifact@v3
        with:
          name: revanced-manager_compose
          path: ./revanced_manager_compose_signed-debug.apk
          if-no-files-found: ignore

      - name: Send revanced patched apk to telegram
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          curl -X POST -H "content-type: multipart/form-data" -F document=@"./revanced_signed.apk" -F chat_id=${CHAT_ID} https://api.telegram.org/bot${BOT_TOKEN}/sendDocument
        shell: bash

      - name: Upload patch log
        uses: actions/upload-artifact@v3
        with:
          name: PatchLog
          path: ./Patch.log
          if-no-files-found: error

      - name: Send revanced patch log to telegram
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          curl -X POST -H "content-type: multipart/form-data" -F document=@"./Patch.log" -F chat_id=${CHAT_ID} https://api.telegram.org/bot${BOT_TOKEN}/sendDocument
        shell: bash

